require('dotenv').config();
const express=require('express');const cors=require('cors');const app=express();
app.use(cors());app.use(express.json({limit:'25mb'}));app.use(express.urlencoded({extended:true}));
app.get('/',(req,res)=>res.json({success:true,sistema:'EXELARIS Tickets API',estado:'Activo'}));
app.get('/health',(req,res)=>res.json({success:true,message:'API funcionando'}));
app.use('/api/eventos',require('./routes/eventos'));
app.use('/api/boletos',require('./routes/boletos'));
app.use('/api/validar',require('./routes/validar'));
app.use('/api/upload',require('./routes/upload'));
app.use('/api/dashboard',require('./routes/dashboard'));
app.use('/api/compras',require('./routes/compras'));
app.use('/api/taquilla',require('./routes/taquilla'));
app.use('/api/lotes',require('./routes/lotes'));
app.use('/api/acceso',require('./routes/acceso'));
app.use('/api/inventario',require('./routes/inventario'));
const PORT=process.env.PORT||3000;app.listen(PORT,()=>console.log(`✅ Servidor EXELARIS corriendo en puerto ${PORT}`));
