const EstadoCompra={evento:null,general:0,vip:0,comprador:{nombre:"",correo:"",telefono:""},asistentes:[]};
document.addEventListener("DOMContentLoaded",async()=>{try{await cargarComponentes();await inicializarApp();document.getElementById("app-loader").style.display="none";document.getElementById("app").classList.remove("hidden");}catch(error){console.error(error);document.getElementById("app-loader").innerHTML='<div class="loader-card"><div class="loader-logo">!</div><p>Error al cargar EXELARIS</p></div>';}});
async function inicializarApp(){const eventos=await Api.obtenerEventos();const eventoActivo=eventos.find(evento=>evento.activo===true);if(!eventoActivo){throw new Error("No hay evento activo");}EstadoCompra.evento=eventoActivo;renderEvento(eventoActivo);inicializarContadores();inicializarFormularioComprador();actualizarResumen();}
function renderEvento(evento){const flyer=evento.flyer||"img/placeholder.jpg";const heroBg=document.querySelector("[data-hero-bg]");if(heroBg){heroBg.style.backgroundImage=`url('${flyer}')`;}document.querySelectorAll("[data-evento-nombre]").forEach(el=>{el.textContent=evento.nombre||"Evento EXELARIS";});document.querySelectorAll("[data-evento-fecha]").forEach(el=>{el.textContent=evento.fecha||"";});document.querySelectorAll("[data-evento-hora]").forEach(el=>{el.textContent=evento.hora||"";});document.querySelectorAll("[data-evento-lugar]").forEach(el=>{el.textContent=evento.lugar||"";});document.querySelectorAll("[data-evento-direccion]").forEach(el=>{el.textContent=evento.direccion||"";});document.querySelectorAll("[data-evento-ciudad]").forEach(el=>{el.textContent=evento.ciudad||"";});document.querySelectorAll("[data-precio-general]").forEach(el=>{el.textContent=`$${evento.precioGeneral||0} MXN`;});document.querySelectorAll("[data-precio-vip]").forEach(el=>{el.textContent=`$${evento.precioVIP||0} MXN`;});}
function inicializarContadores(){document.querySelectorAll("[data-ticket-control]").forEach(control=>{const tipo=control.dataset.ticketControl;const menos=control.querySelector("[data-minus]");const mas=control.querySelector("[data-plus]");const valor=control.querySelector("[data-value]");menos.addEventListener("click",()=>{EstadoCompra[tipo]=Math.max(0,EstadoCompra[tipo]-1);valor.textContent=EstadoCompra[tipo];actualizarResumen();renderAsistentes();});mas.addEventListener("click",()=>{const totalActual=EstadoCompra.general+EstadoCompra.vip;if(totalActual>=10){alert("Máximo 10 boletos por compra");return;}EstadoCompra[tipo]++;valor.textContent=EstadoCompra[tipo];actualizarResumen();renderAsistentes();});});}
function inicializarFormularioComprador(){const nombre=document.getElementById("compradorNombre");const correo=document.getElementById("compradorCorreo");const telefono=document.getElementById("compradorTelefono");[nombre,correo,telefono].forEach(input=>{input.addEventListener("input",()=>{EstadoCompra.comprador.nombre=nombre.value.trim();EstadoCompra.comprador.correo=correo.value.trim();EstadoCompra.comprador.telefono=telefono.value.trim();});});}
function renderAsistentes(){const contenedor=document.getElementById("asistentesLista");if(!contenedor){return;}const total=EstadoCompra.general+EstadoCompra.vip;EstadoCompra.asistentes=Array.from({length:total},(_,index)=>EstadoCompra.asistentes[index]||{nombre:"",tipo:index<EstadoCompra.general?"General":"VIP"});contenedor.innerHTML="";if(total===0){contenedor.innerHTML='<p class="text-slate-500 font-semibold">Selecciona boletos para capturar asistentes.</p>';return;}EstadoCompra.asistentes.forEach((asistente,index)=>{const card=document.createElement("div");card.className="asistente-card";card.innerHTML=`<div class="field"><label>Boleto ${index+1} - ${asistente.tipo}</label><input type="text" placeholder="Nombre del asistente" value="${asistente.nombre}" data-asistente-index="${index}"></div>`;contenedor.appendChild(card);});contenedor.querySelectorAll("[data-asistente-index]").forEach(input=>{input.addEventListener("input",()=>{const index=Number(input.dataset.asistenteIndex);EstadoCompra.asistentes[index].nombre=input.value.trim();});});}
function actualizarResumen(){const evento=EstadoCompra.evento;if(!evento){return;}const totalGeneral=EstadoCompra.general*(evento.precioGeneral||0);const totalVip=EstadoCompra.vip*(evento.precioVIP||0);const total=totalGeneral+totalVip;document.querySelectorAll("[data-resumen-general]").forEach(el=>{el.textContent=EstadoCompra.general;});document.querySelectorAll("[data-resumen-vip]").forEach(el=>{el.textContent=EstadoCompra.vip;});document.querySelectorAll("[data-resumen-total]").forEach(el=>{el.textContent=`$${total} MXN`;});}
function irACompra(){document.getElementById("boletos").scrollIntoView({behavior:"smooth"});}
